# Generated by Django 5.1.1 on 2025-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_transcribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptionresult',
            old_name='transcription',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='transcriptionresult',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='transcriptionresult',
            name='medical_entities',
            field=models.JSONField(),
        ),
    ]
