# Generated by Django 5.1.1 on 2025-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_transcribe', '0002_rename_transcription_transcriptionresult_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptionresult',
            old_name='text',
            new_name='transcription',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='transcription',
        ),
        migrations.AlterField(
            model_name='transcriptionresult',
            name='medical_entities',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
